services:
  onlinebookstore:
    container_name: onlinebookstoreApp
    image: ${DOCKER_REGISTRY-}onlinebookstore:1.0
    build:
      context: .
      dockerfile: OnlineBookStore/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=onlinebookstore_db;Database=OnlineBookStore;User Id=sa;Password=BookStore2025!;Trust Server Certificate=True;
    depends_on:
      - onlinebookstoreDB
    networks:
      - onlinebookstore

  onlinebookstoreDB:
    container_name: onlinebookstore_db   
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BookStore2025!
    networks:
      - onlinebookstore
    volumes:
      - bookstoreVolume:/var/opt/mssql

volumes:
    bookstoreVolume:

networks:
    onlinebookstore:
        driver: bridge